### ISSUE TITLE
training  error

### ISSUE THREAD

**Issue by fcu-d0449079** [naoto0804/SynShadow#16] opened 2022-04-02 05:32 UTC
Thank you for sharing. I want to train spmnet on ISTD, but I got the error after some epochs:

C:\anaconda\envs\taka1\lib\site-packages\numpy\lib\polynomial.py:628: RuntimeWarning: invalid value encountered in true_divide
  lhs /= scale

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGELSD.
Traceback (most recent call last):
  File "train.py", line 31, in <module>
    for i, data_i in enumerate(dataloader, start=iter_counter.epoch_iter):
  File "C:\anaconda\envs\taka1\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\anaconda\envs\taka1\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\anaconda\envs\taka1\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\anaconda\envs\taka1\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\SynShadow\src\data\paired_dataset.py", line 82, in __getitem__
    return self.postprocess(input_dict)
  File "C:\SynShadow\src\data\base_dataset.py", line 49, in postprocess
    d['input'], d['target'], d['mask'].squeeze())
  File "C:\SynShadow\src\util\illum_affine_model.py", line 98, in fit_brightening_params
    1
  File "<__array_function__ internals>", line 6, in polyfit
  File "C:\anaconda\envs\taka1\lib\site-packages\numpy\lib\polynomial.py", line 629, in polyfit
    c, resids, rank, s = lstsq(lhs, rhs, rcond)
  File "<__array_function__ internals>", line 6, in lstsq
  File "C:\anaconda\envs\taka1\lib\site-packages\numpy\linalg\linalg.py", line 2306, in lstsq
    x, resids, rank, s = gufunc(a, b, rcond, signature=signature, extobj=extobj)
  File "C:\anaconda\envs\taka1\lib\site-packages\numpy\linalg\linalg.py", line 100, in _raise_linalgerror_lstsq
    raise LinAlgError("SVD did not converge in Linear Least Squares")
numpy.linalg.LinAlgError: SVD did not converge in Linear Least Squares

Thanks.  
I revise code in illum_affine_model.py line 100 except ValueError: -> except :
Then, I didn't get error.

---------------------------------------------------------------
On the other hand, when I trained spmnet on ISTD,w_l2 and b_l2 loss decreased fastly, but L1 loss didn't decrease. The results from this checkpoints are bad.
I trained spmnet on SynShadow(USR/shadowfree). W_l2 and b_l2 loss decreased slowly, and L1 loss also decreased. The results are good.

In addition,do you have some validation set to evaluate benchmark during training?

**Comment by naoto0804** [comment] 2022-04-11 12:50
1. code modification
It seems OK but be careful you might ignore some errors that should be fixed.

2. bad results on ISTD
I haven't tested SP+M on the original ISTD dataset, since there is a non-negligible level of brightness inconsistencies between paired shadow/non-shadow images.
Have you tried ISTD+, where the problem is fixed?

3. Do you have some validation set to evaluate the benchmark during training?
I did not have it, but you can make it by splitting the data to keep some shadow-free and matte images only for validation.
Note that the performance on the 'synthetic' validation set may not highly correlate with the performance on the 'real' validation set due to the distribution change.

**Closed as completed** 2022-04-11 12:50 UTC
